# Generated by Django 3.2.3 on 2021-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categoria',
            field=models.CharField(choices=[('Ciências', 'Ciências'), ('Matemática', 'Matemática'), ('História', 'História')], max_length=200, null=True),
        ),
    ]
