# Generated by Django 3.2.3 on 2021-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_who_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='liked',
            field=models.ManyToManyField(to='polls.Customer'),
        ),
    ]
