# Generated by Django 3.2.3 on 2021-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210605_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike', to='polls.Customer'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='liked',
            field=models.ManyToManyField(related_name='like', to='polls.Customer'),
        ),
    ]
